apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: crm-customer
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      name: crm-customer
      labels:
        app: crm-customer
    spec:
      containers:
      - name: crm-customer
        image: malditoidealismo/crm-customer
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
        env:
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres_user
          - name: POSTGRES_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres_password
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                name: hostname-config
                key: postgres_host
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "300Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: customer-service
spec:
  type: NodePort
  selector:
    app: crm-customer
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30002