apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spring-boot-postgres
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      name: spring-boot-postgres
      labels:
        app: spring-boot-postgres
    spec:
      containers:
      - name: spring-boot-postgres
        env:
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres_user
          - name: POSTGRES_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres_password
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                name: hostname-config
                key: postgres_host
        image: superdev-crm-customer
