server:
  port: 8001

spring:
  application:
    name: categoria_producto

  #Mongodb
  data:
    mongodb:
      database: categoria_producto
      host: localhost
      port: 27017

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

eureka:
  client:
    service-url:
      defaultZone: http://${registry.host:localhost}:${registry.port:8000}/eureka/

#Actuator
management:
  endpoints:
    web:
      exposure:
        include: info
info:
  app:
    name: ${spring.application.name}
    description: "Microservicio de categoria y producto"
  java_version: ${java.specification.version}
