server:
  port: 3001

spring:
  application:
    name: kafka_listener

  kafka:
    consumer:
      bootstrap-servers: 34.68.95.248:9092
      group-id: com.martinsaman
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
topic:
  name: DatabaseTopic

feign:
  hystrix:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://${registry.host:localhost}:${registry.port:8000}/eureka/

#Actuator
management:
  endpoints:
    web:
      exposure:
        include: info
info:
  app:
    name: ${spring.application.name}
    description: "Microservicio de producer para kafka"
  java_version: ${java.specification.version}
