version: "3.8"
services:
  postgres-server:
    image: "postgres:10-alpine"
    container_name: "postgres-server"
    env_file:
      - dev.env
    ports:
      - "5432:5432"
    networks:
      microservice_network:

  crm-customer:
    build: .
    env_file:
      - dev.env
    ports:
      - "8080:8080"
    depends_on:
      - "postgres-server"
    networks:
      microservice_network:

networks:
  microservice_network:
    ipam:
      driver: default