version: "3.8"
services:
  postgres-server:
    image: "postgres:10-alpine"
    container_name: "postgres-server"
    environment:
     - POSTGRES_USER=superdevuser
     - POSTGRES_PASSWORD=P@ssword1
     - POSTGRES_DB=superdevdb
    ports:
      - "5432:5432"
    networks:
      microservice_network:
  
  superdev-crm-customer:
    build: ./superdev-crm-customer-part2
    ports:
      - "8080:8080"
    networks:
      microservice_network:

networks:
  microservice_network:
    ipam:
      driver: default