version: "3"
services:
  # Kafka
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 23.102.156.137
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "email_topic:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # Microservicios
  email:
    build: ./email-service
    container_name: email-service

  user:
    build: ./user-service
    container_name: user-service
    ports:
      - "3005:3005"

  course:
    build: ./course-service
    container_name: course-service
    ports:
      - "3007:3007"

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - user
      - course






  # Base de datos
  #mongo-users:
  #  container_name: mongo-users
  #  image: mongo
  #  volumes:
  #    - ./data:/data/db
  #  expose:
  #    - "27010:27017"
  #mongo-courses:
  #  container_name: mongo-courses
  #  image: mongo
  #  volumes:
  #    - ./data:/data/db
  #  expose:
  #    - "27011:27017"
